### ISSUE TITLE
please set returncode according to file(s) OK or not

### ISSUE THREAD

**Issue by bittorf** [lucasdemarchi/codespell#63]
no errors = 0 and errors found should give >0.

for now it always succeeds:
```
user@box:~# ./codespell.py -i 0 $FILE
(several mistakes)
user@box:~# echo $?
0
```
but i exspect e.g. '1'

**Comment by Eric89GXL** [comment]
FYI right now I do `codespell.py ... | tee /dev/tty | wc -l | xargs test 0 -eq` to get it to print the result and give a meaningful error code.

**Comment by lucasdemarchi** [comment]
yeah... we should return an error code. Anyone up to send a patch for this?

**Comment by Eric89GXL** [comment]
[Sure] (https://github.com/lucasdemarchi/codespell/issues/64#issuecomment-213420353) :)

**Comment by thorade** [comment]
Sorry for commenting on an old issue: I would be interested in two examples, showing:
* How to call codespell from python (script or notebook) and
* How to ceck the return code from that script.

If you happen to have such an example it would be greatly appreciated, otherwise I would try how far I can get myself.
