### ISSUE TITLE
ImportError: No module named codespell_lib

### ISSUE THREAD

**Issue by claudiu-cristea** [lucasdemarchi/codespell#75]
I downloaded the script and ran it as:

```
$ ./vendor/lucasdemarchi/codespell/bin/codespell.py -h
```
but it gives:
```
Traceback (most recent call last):
  File "./vendor/lucasdemarchi/codespell/bin/codespell.py", line 6, in <module>
    import codespell_lib
ImportError: No module named codespell_lib
```

If I copy codespell.py one directory up and run that, it works.

**Comment by Eric89GXL** [comment]
It's no longer a self-contained single file. If you do a standard Python library install, it should work properly.

@lucasdemarchi should we try to do a PyPi release (#38) so that people can do `pip install codespell`? If you don't mind, I already have released some packages on PyPi so I could take care of it. I'd then immediately start using `pip install codespell` in my CI-tested repos so it would be nicely tested.

**Comment by claudiu-cristea** [comment]
@Eric89GXL, I'm using in a PHP project where I'm installing as a composer dependency. I don't know how to install it in this case as a library. I see no instructions in the README.

**Comment by lucasdemarchi** [comment]
Yes, please. Go ahead and do a release. I also added you as a collaborator
in this repository. You can also merge the PRs if you find they are correct.
Em 9 de jun de 2016 10:39 AM, "Eric Larson" <notifications@github.com>
escreveu:

**Comment by Eric89GXL** [comment]
> You can also merge the PRs if you find they are correct.

Trying to relieve some review burden, eh? :) Will do.

**Comment by lucasdemarchi** [comment]
Em 9 de jun de 2016 2:45 PM, "Eric Larson" <notifications@github.com>
escreveu:
>>
>> You can also merge the PRs if you find they are correct.
>
> Trying to relieve some review burden, eh? :) Will do.

You are already reviewing and doing an awesome job.
