### ISSUE TITLE
ImportError: No module named 'codespell_lib'

### ISSUE THREAD

**Issue by gemal** [lucasdemarchi/codespell#87]
I using codespell on scrutinizer which is a ci

unfortunately it doesn't work

My commands are:
```
pip install codespell

Collecting codespell
  Downloading codespell-1.9.2.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 4.2MB/s 
25hBuilding wheels for collected packages: codespell
  Running setup.py bdist_wheel for codespell ... 25l- done
25h  Stored in directory: /home/scrutinizer/.cache/pip/wheels/20/42/eb/32e6da9b97cf208b6e9cecaaf9c08e324f1826a136c721637f
Successfully built codespell
Installing collected packages: codespell
Successfully installed codespell-1.9.2
```

if I then try to run the command with something like:

```
python ../bin/codespell.py app/Config/core.php
The command exited with code 1.

Traceback (most recent call last):
  File "../bin/codespell.py", line 6, in 
    import codespell_lib
ImportError: No module named 'codespell_lib'
```

it doesn't work untill I add a full path to PYTHONPATH which I dont think is expected

**Comment by Eric89GXL** [comment]
That sounds like a misconfigured `python` environment. Is the `pip` that you're using the same one that `python` will eventually use? Some `which pip`, `which python` should help. After doing `pip install codespell`, doing `python -c "import codespell_lib` should work.

As a side note, you also shouldn't need to do `$ python ../bin/codespell.py file`, but rather just `codespell.py file`, since it should be in a usable `bin` directory after `pip` installs it.

**Comment by gemal** [comment]
```
which pip
/home/scrutinizer/.pyenv/shims/pip

which python
/home/scrutinizer/.pyenv/shims/python

codespell.py -h
-bash: codespell.py: command not found

find / -name codespell_lib 
/home/scrutinizer/build/dinnerbooking.com/lib/python3.4/site-packages/codespell_lib

```

**Comment by Eric89GXL** [comment]
Can you also do `python -c "import sys; import pprint; pprint.pprint(sys.path)"`? I suspect `/home/scrutinizer/build/xxxx.com/lib/python3.4/site-packages/` will not be in the list.

And can you try `python -c "import codespell_lib"`? That one should succeed if the above mentioned path is in `sys.path`.

**Comment by gemal** [comment]
I had some wrong code on my part
